/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package genar;

import java.io.File;
import java.io.FileWriter;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;

/**
 *
 * @author pzanelli
 */
public class archivoCanje extends javax.swing.JFrame {
	
    /**
     * Creates new form cabtdreip
     */

    public archivoCanje() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lincabt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        codInter = new javax.swing.JLabel();
        tipInter = new javax.swing.JLabel();
        nroEnvio = new javax.swing.JLabel();
        nroCorrel = new javax.swing.JLabel();
        tipoItem = new javax.swing.JLabel();
        numBol = new javax.swing.JLabel();
        numChe = new javax.swing.JLabel();
        correCheque = new javax.swing.JLabel();
        bcoLib = new javax.swing.JLabel();
        sucBcoLib = new javax.swing.JLabel();
        codPostal = new javax.swing.JLabel();
        local = new javax.swing.JLabel();
        ctaLibradora = new javax.swing.JLabel();
        empCorresp = new javax.swing.JLabel();
        bancoCorres = new javax.swing.JLabel();
        sucBancoCorres = new javax.swing.JLabel();
        pzoEnHs = new javax.swing.JLabel();
        sucDeposito = new javax.swing.JLabel();
        mdaDeposito = new javax.swing.JLabel();
        fecDepo = new javax.swing.JLabel();
        fecVencValor = new javax.swing.JLabel();
        trunc = new javax.swing.JLabel();
        impCheque = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        impCheque1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rechazos Camara Enviada en Pesos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(lincabt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 688, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pegar aqui la linea del cheque del archivo CABTDCEIP.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 11, -1, -1));

        jButton1.setText("Leer linea");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 690, -1));

        codInter.setText("0");
        getContentPane().add(codInter, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 88, -1));

        tipInter.setText("0");
        getContentPane().add(tipInter, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 88, -1));

        nroEnvio.setText("0");
        getContentPane().add(nroEnvio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 88, -1));

        nroCorrel.setText("0");
        getContentPane().add(nroCorrel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 88, -1));

        tipoItem.setText("0");
        getContentPane().add(tipoItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 88, -1));

        numBol.setText("0");
        getContentPane().add(numBol, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 88, -1));

        numChe.setText("0");
        getContentPane().add(numChe, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 88, -1));

        correCheque.setText("0");
        getContentPane().add(correCheque, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 88, -1));

        bcoLib.setText("0");
        getContentPane().add(bcoLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 88, -1));

        sucBcoLib.setText("0");
        getContentPane().add(sucBcoLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 88, -1));

        codPostal.setText("0");
        getContentPane().add(codPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 88, -1));

        local.setText("0");
        getContentPane().add(local, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 88, -1));

        ctaLibradora.setText("0");
        getContentPane().add(ctaLibradora, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 81, 195, -1));

        empCorresp.setText("0");
        getContentPane().add(empCorresp, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 101, 195, -1));

        bancoCorres.setText("0");
        getContentPane().add(bancoCorres, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 121, 195, -1));

        sucBancoCorres.setText("0");
        getContentPane().add(sucBancoCorres, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 141, 162, -1));

        pzoEnHs.setText("0");
        getContentPane().add(pzoEnHs, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 161, 195, -1));

        sucDeposito.setText("0");
        getContentPane().add(sucDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 181, 195, -1));

        mdaDeposito.setText("0");
        getContentPane().add(mdaDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 201, 195, -1));

        fecDepo.setText("0");
        getContentPane().add(fecDepo, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 221, 195, -1));

        fecVencValor.setText("0");
        getContentPane().add(fecVencValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 241, 195, -1));

        trunc.setText("0");
        getContentPane().add(trunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 261, 195, -1));

        impCheque.setText("0");
        getContentPane().add(impCheque, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 100, -1));

        jLabel4.setText("Código de Interface");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 81, -1, -1));

        jLabel5.setText("Tipo de interface");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 101, -1, -1));

        jLabel2.setText("Número de envío");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 121, -1, -1));

        jLabel3.setText("Correlativo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 141, -1, -1));

        jLabel6.setText("Tipo de Ítem");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 161, -1, -1));

        jLabel7.setText("Número de Boleta");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 181, -1, -1));

        jLabel8.setText("Número del cheque");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 201, -1, -1));

        jLabel9.setText("Cheques en boleta");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel10.setText("Sucursal de deposito");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel11.setText("Moneda del Deposito");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel12.setText("Fecha del deposito");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jLabel13.setText("Fecha de vencimiento");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jLabel14.setText("Importe de la Boleta");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, -1));

        jLabel15.setText("Importe indicado por el Proveedor");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        jLabel16.setText("Empresa Bantotal");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        jLabel17.setText("Sucursal Bantotal");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

        jLabel18.setText("Modulo Bantotal");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, -1));

        jLabel19.setText("Cuenta Bantotal");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        jLabel20.setText("Moneda Bantotal");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, -1));

        jLabel21.setText("Papel Bantotal");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, -1));

        jLabel22.setText("Operación Bantotal");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));

        jLabel23.setText("Sub Operación Bantotal");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, -1));

        jLabel24.setText("Tipo de Operación");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, -1, -1));

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, -1, -1));

        jButton2.setText("Leer Linea");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, -1));

        jLabel37.setText("Rubro");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, -1, -1));

        impCheque1.setText("0");
        getContentPane().add(impCheque1, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 281, 195, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        
        
        String lineacabt = lincabt.getText();
        System.out.println(lineacabt);
        
        String aCodInt = lineacabt.substring(0,3);
        codInter.setText(aCodInt);

        String aTipInt = lineacabt.substring(3,6);
        tipInter.setText(aTipInt);
        
        String nroEnvi = lineacabt.substring(6,15);
        nroEnvio.setText(nroEnvi);
        
        String nroCorre = lineacabt.substring(15,21);
        nroCorrel.setText(nroCorre);
        
        String tpoItem = lineacabt.substring(21,28);
        tipoItem.setText(tpoItem);
       
        String nroBoleta = lineacabt.substring(28, 37);
        numBol.setText(nroBoleta);
       
        String nroCheque = lineacabt.substring(37,57);
        numChe.setText(nroCheque);
       
        String corrCheque = lineacabt.substring(57, 70);
        correCheque.setText(corrCheque);
       
        String bcoLibr = lineacabt.substring(70, 74);
        bcoLib.setText(bcoLibr);
       
        String sucBco = lineacabt.substring(74, 82);
        sucBcoLib.setText(sucBco);
       
        String codPos = lineacabt.substring(82, 90);
        codPostal.setText(codPos);
       
        String localidad = lineacabt.substring(90, 108);
        local.setText(localidad);
       
        String ctaLibra = lineacabt.substring(108, 126);
        ctaLibradora.setText(ctaLibra);
       
        String empresaCorre = lineacabt.substring(126, 129);
        empCorresp.setText(empresaCorre);
        
        String bcoCorresp = lineacabt.substring(129, 132);
        bancoCorres.setText(bcoCorresp);
        
        String sucBcoCorresp = lineacabt.substring(132, 135);
        sucBancoCorres.setText(sucBcoCorresp);
        
        String pzoHs = lineacabt.substring(135, 144);
        pzoEnHs.setText(pzoHs);
        
        String sucDepo = lineacabt.substring(144, 148);
        sucDeposito.setText(sucDepo);  
        
        String mdaDepo = lineacabt.substring(148, 152);
        mdaDeposito.setText(mdaDepo); 
        
        String fechDepo = lineacabt.substring(152, 161);
        fecDepo.setText(fechDepo);
        
        String fechVencValor = lineacabt.substring(161, 164);
        fecVencValor.setText(fechVencValor);
        
        String truncado = lineacabt.substring(164, 167);
        trunc.setText(truncado);
        
        String importeCheque = lineacabt.substring(167, 183);
        impCheque.setText(importeCheque);
        
        
       



         
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try
        {
            String texto = "CABTDREIP.txt";
            File archivo=new File(texto);         //Le damos el nombre al archivo y la extension
            
            
            
            
            
            
            
            
            if (archivo.exists()) {
                   archivo.delete();
               }
            
                        try (FileWriter escribir = new FileWriter(archivo,true)) {
                //Escribimos en el archivo con el metodo write
                        String lineacabt = lincabt.getText();
                        String graba = lineacabt.substring(0, 3);
                        String codigo = "003";                             
                        String grabado = lineacabt.substring(6, 233);
                        
                        
                        String relleno = "00";
                        String relleno2 = "                                                  ";
                        String relleno3 = "                                                  ";
                        String relleno4 = "                                                  ";
                        String relleno5 = "00000000";
                        
                escribir.write(graba+codigo+grabado+relleno+relleno2+relleno3+relleno4+relleno5+"\r\n");
            }
                        //Lo utilizamos para limpiar los textFields

            this.dispose();
            new agregar(this, true).setVisible(true);
        }


        //En caso de error.
        catch(Exception e)
        {
            System.out.println("Error al escribir");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(archivoCanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(archivoCanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(archivoCanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(archivoCanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new archivoCanje();
                frame.setVisible(true);
                frame.setLocationRelativeTo(null);
                
                
            }
            
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bancoCorres;
    private javax.swing.JLabel bcoLib;
    private javax.swing.JLabel codInter;
    private javax.swing.JLabel codPostal;
    private javax.swing.JLabel correCheque;
    private javax.swing.JLabel ctaLibradora;
    private javax.swing.JLabel empCorresp;
    private javax.swing.JLabel fecDepo;
    private javax.swing.JLabel fecVencValor;
    private javax.swing.JLabel impCheque;
    private javax.swing.JLabel impCheque1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lincabt;
    private javax.swing.JLabel local;
    private javax.swing.JLabel mdaDeposito;
    private javax.swing.JLabel nroCorrel;
    private javax.swing.JLabel nroEnvio;
    private javax.swing.JLabel numBol;
    private javax.swing.JLabel numChe;
    private javax.swing.JLabel pzoEnHs;
    private javax.swing.JLabel sucBancoCorres;
    private javax.swing.JLabel sucBcoLib;
    private javax.swing.JLabel sucDeposito;
    private javax.swing.JLabel tipInter;
    private javax.swing.JLabel tipoItem;
    private javax.swing.JLabel trunc;
    // End of variables declaration//GEN-END:variables
}
