/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package genar;
import genar.cabtdceipArchivo.Variable;
import java.io.File;
import java.io.FileWriter;

/**
 *
 * @author pzanelli
 */
public class CABTDCEIP1 extends javax.swing.JFrame {

    
    
        int fechaAcr = Integer.parseInt(Variable.fecha);
    
    
    /**
     * Creates new form camararecibida
     */
    public CABTDCEIP1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        numCheque = new javax.swing.JTextField();
        fechaAcdred = new javax.swing.JTextField();
        tipoOpera = new javax.swing.JTextField();
        subOperacion = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        bcoCorresponsal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ctaBt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        sucBtal = new javax.swing.JTextField();
        importeCheque = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Canje Interno CABTDCEIP");
        setAlwaysOnTop(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Generación archivo para generar archivo CABTDCEIP");

        jLabel2.setText("Número de Cheque");

        jLabel3.setText("Fecha de Acreditación");

        jLabel5.setText("Tipo de operacion");

        jLabel6.setText("Sub Cuenta");

        fechaAcdred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaAcdredActionPerformed(evt);
            }
        });

        jButton1.setText("Generar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Banco Corresponsal");

        jLabel10.setText("Cuenta Bantotal");

        jLabel11.setText("Sucursal Bantotal");

        jLabel4.setText("Importe del Cheque");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fechaAcdred)
                            .addComponent(tipoOpera, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subOperacion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numCheque, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bcoCorresponsal, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ctaBt)
                            .addComponent(sucBtal)
                            .addComponent(importeCheque)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(bcoCorresponsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaAcdred, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(importeCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctaBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sucBtal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tipoOpera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String codInt = "003"; //S 
        String tipInt = "002"; //S
        String numEnv = Variable.nroEnvio1; //s
        String corre = "0000000001"; //s
        String tipItem = "002"; //s
        String numBole = Variable.nroBoleta; //s
        String numCheque1 = numCheque.getText();  // 
        String correCheque = "000000000435321"; // 
        String bcoLibra = bcoCorresponsal.getText(); // 
        String sucBcoLibra = "363"; //
        String codPosta = "3116        ";//
        String localidad = "460"; //
        String ctaLibra = "000000000045042"; //
        String empresa = "027";
        String bcoCorrespon = bcoCorresponsal.getText();
        String sucCorresp = "001"; // 
        String pzoHs = "024";
        String sucDepo = "100";    
        String mdaDepo = "0080"; //Completar con 8 digitos
        String fechaDeposit = Variable.fecha;
        String fechaAcredita = fechaAcdred.getText();
        String trunca = "N"; // 
        String importeChq = importeCheque.getText();
        //String imporChqPro = importeChq;
        String empresaBt = "001";
        String sucBt = sucBtal.getText();
        String modBt = "020";
        String ctaBt1 = ctaBt.getText();
        String mdaBantotal = "0080";
        String papBt = "0000";
        String operBt = "000000000";
        String subOper = subOperacion.getText();
        String tpoOper = tipoOpera.getText();
        String rubro = "0000000311724001";
        String relleno = "00000                                                                                                                                                      00000000";
        
        
      
        

        try
        {
            String texto = "CABTDCEIP.txt";
            File archivo=new File(texto);         //Le damos el nombre al archivo y la extension
                                    //Comprobamos que si el archivo exista, lo borre. 

            

            String numChq2 = String.format("%015d", Integer.parseInt(numCheque1));
            String bcoCorrespon2 = String.format("%03d", Integer.parseInt(bcoCorrespon));
            String fechaAcredita2 = String.format("%08d", Integer.parseInt(fechaAcredita));            
            String importeChq2 = String.format("%018d", Integer.parseInt(importeChq));            
            String sucBt2 = String.format("%03d", Integer.parseInt(sucBt));            
            String ctaBt12 = String.format("%09d", Integer.parseInt(ctaBt1));
            String subOper2 = String.format("%03d", Integer.parseInt(subOper));
            String tpoOper2 = String.format("%03d", Integer.parseInt(tpoOper));
            String bcoLibra2 = String.format("%03d", Integer.parseInt(bcoLibra));

            
            //Importe proveedor igual al importe de boleta
            
            
            
            //Comprobamos que si el archivo exista, lo borre. 
                        if (archivo.exists()) {
                   archivo.delete();
               }
                        try (FileWriter escribir = new FileWriter(archivo,true)) {
                //Escribimos en el archivo con el metodo write                          
                escribir.write(codInt+tipInt+numEnv+corre+tipItem+numBole+numChq2+correCheque+bcoLibra2+sucBcoLibra+
                        codPosta+localidad+ctaLibra+empresa+bcoCorrespon2+sucCorresp+pzoHs+sucDepo+mdaDepo+fechaDeposit+fechaAcredita2+
                        trunca+importeChq2+importeChq2+empresaBt+sucBt2+modBt+ctaBt12+mdaBantotal+papBt+operBt+subOper2+tpoOper2+rubro+relleno+"\r\n");
            }
                        //Lo utilizamos para limpiar los textFields

            this.dispose();
            new agregarchqcanje2(this, true).setVisible(true);
        }
        //En caso de error.
        catch(Exception e)
        {
            System.out.println("Error al escribir");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void fechaAcdredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaAcdredActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaAcdredActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CABTDCEIP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CABTDCEIP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CABTDCEIP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CABTDCEIP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CABTDCEIP1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bcoCorresponsal;
    private javax.swing.JTextField ctaBt;
    private javax.swing.JTextField fechaAcdred;
    private javax.swing.JTextField importeCheque;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField numCheque;
    private javax.swing.JTextField subOperacion;
    private javax.swing.JTextField sucBtal;
    private javax.swing.JTextField tipoOpera;
    // End of variables declaration//GEN-END:variables
}
