/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package genar;

import java.io.File;
import java.io.FileWriter;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;

/**
 *
 * @author pzanelli
 */
public class cabtdreid extends javax.swing.JFrame {
	
    /**
     * Creates new form cabtdreip
     */

    public cabtdreid() {
        initComponents();
        jPanel1.setVisible(false);
        combo1.setModel(new DefaultComboBoxModel<>(new String[]{"CUENTA EMBARGADA",
            "CTA.CERRADA P/ORDEN JUDIC.", "CUENTA INEXISTENTE", "NRO. DE CUENTA INVALIDO",
            "ORDEN DE DIFERIMIENTO", "DEFECTOS FORMALES", "ORDEN DE NO PAGAR",
            "SIN FDOS.SUFICIENTES EN CTA.", "CHEQUE YA ENTREGADO ", "SUC./ENTIDAD INEXISTENTE",
            "ERROR DE FORMATO", "FECHA DE COMPENS. ERRONEA", "IMPORTE ERRONEO", "CONCURSO PREVENTIVO",
            "TRANSACCION DUPLICADA", "ERROR EN REG. ADICIONAL", "ERROR EN CAMPO MANDATORIO"
            , "ERROR EN CONTADOR REG.", "VUELTA ATRAS DE CAMARA", "SITUACION DE EMERGENCIA"
            , "FALTA CONFORMIDAD DE CHEQUERA", "IMP. DISTINTO A TRANS ORIGINAL",
            "CHEQ.EXTRAVIADO NO ENTREGADO", "NO INDICO NRO. DE CHEQUE",
            "FECHA INVALIDA", "ERROR CAMPO 11 CAB. DE LOTE", "ERROR CAMPO 4 REGISTRO INDIV.",
            "ERROR CAMPO 5 REGISTRO INDIV.", "ERROR CAMPO 7 REGISTRO INDIV.",
            "ERROR CAMPO 3 REG. ADICIONAL", "FUERZA MAYOR", "CHEQUE FALTANTE",
            "MONEDA INVALIDA", "ERROR CAMPO 2 REG. INDIVIDUAL",  "TRX. NO CORR. NO EX. ORIG.",
            "COD. BCO. NO COMPAT. C/MONEDA", "NRO. MAX. ORD. DIFER. EXCED.",
            "DIA NO LABORABLE", "CODIGO POSTAL ERRONEO", "REVERSION YA EFECTUADA",
            "FERIADO LOCAL", "IMAGEN ILEGIBLE"}));
        //String arregloItems[]=new String[]{"Seleccione","Opcion1","Opcion2"};
        //combo1.setModel(new DefaultComboBoxModel<>(arregloItems));

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lincabt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        codInter = new javax.swing.JLabel();
        tipInter = new javax.swing.JLabel();
        nroEnvio = new javax.swing.JLabel();
        nroCorrel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tipoItem = new javax.swing.JLabel();
        numBol = new javax.swing.JLabel();
        numChe = new javax.swing.JLabel();
        correCheque = new javax.swing.JLabel();
        bcoLib = new javax.swing.JLabel();
        sucBcoLib = new javax.swing.JLabel();
        codPostal = new javax.swing.JLabel();
        local = new javax.swing.JLabel();
        ctaLibradora = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        empCorresp = new javax.swing.JLabel();
        bancoCorres = new javax.swing.JLabel();
        sucBancoCorres = new javax.swing.JLabel();
        pzoEnHs = new javax.swing.JLabel();
        sucDeposito = new javax.swing.JLabel();
        mdaDeposito = new javax.swing.JLabel();
        fecDepo = new javax.swing.JLabel();
        fecVencValor = new javax.swing.JLabel();
        trunc = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        impCheque = new javax.swing.JLabel();
        vencheque = new javax.swing.JLabel();
        empBantotal = new javax.swing.JLabel();
        sucBantotal = new javax.swing.JLabel();
        modBantotal = new javax.swing.JLabel();
        ctaBantotal = new javax.swing.JLabel();
        mdaBantotal = new javax.swing.JLabel();
        papBantotal = new javax.swing.JLabel();
        opBantotal = new javax.swing.JLabel();
        subOpBantotal = new javax.swing.JLabel();
        tpoOpBantotal = new javax.swing.JLabel();
        rubro = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        combo1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rechazos Camara enviada Dolares");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pegar aquí la línea del cheque del archivo CABTDCEID.");

        jButton1.setText("Leer linea");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Número de envío");

        codInter.setText("0");

        tipInter.setText("0");

        nroEnvio.setText("0");

        nroCorrel.setText("0");

        jLabel3.setText("Correlativo");

        jLabel4.setText("Código de Interface");

        jLabel5.setText("Tipo de interface");

        tipoItem.setText("0");

        numBol.setText("0");

        numChe.setText("0");

        correCheque.setText("0");

        bcoLib.setText("0");

        sucBcoLib.setText("0");

        codPostal.setText("0");

        local.setText("0");

        ctaLibradora.setText("0");

        jLabel6.setText("Tipo de Ítem");

        jLabel7.setText("Número de Boleta");

        jLabel8.setText("Número del cheque");

        jLabel9.setText("Correlativo del cheque ");

        jLabel10.setText("Banco Librador");

        jLabel11.setText("Sucursal banco Librador");

        jLabel12.setText("Código Postal");

        jLabel13.setText("Localidad");

        jLabel14.setText("Cuenta Libradora");

        jLabel15.setText("Empresa corresponsal");

        empCorresp.setText("0");

        bancoCorres.setText("0");

        sucBancoCorres.setText("0");

        pzoEnHs.setText("0");

        sucDeposito.setText("0");

        mdaDeposito.setText("0");

        fecDepo.setText("0");

        fecVencValor.setText("0");

        trunc.setText("0");

        jLabel16.setText("Banco corresponsal");

        jLabel17.setText("Suc. Banco corresponsal");

        jLabel18.setText("Plazo en horas");

        jLabel19.setText("Sucursal donde se depositó");

        jLabel20.setText("Moneda del depósito");

        jLabel21.setText("Fecha del depósito");

        jLabel22.setText("Fecha de vencimiento del valor");

        jLabel23.setText("Truncado");

        impCheque.setText("0");

        vencheque.setText("0");

        empBantotal.setText("0");

        sucBantotal.setText("0");

        modBantotal.setText("0");

        ctaBantotal.setText("0");

        mdaBantotal.setText("0");

        papBantotal.setText("0");

        opBantotal.setText("0");

        subOpBantotal.setText("0");

        tpoOpBantotal.setText("0");

        rubro.setText("0");

        jLabel24.setText("Importe del cheque");

        jLabel25.setText("Importe del cheque indicado por el proveedor");

        jLabel26.setText("Empresa Bantotal");

        jLabel27.setText("Sucursal Bantotal");

        jLabel28.setText("Módulo Bantotal");

        jLabel29.setText("Cuenta Bantotal");

        jLabel30.setText("Moneda Bantotal");

        jLabel31.setText("Papel Bantotal");

        jLabel32.setText("Operación Bantotal");

        jLabel33.setText("Sub Operación Bantotal");

        jLabel34.setText("tipo de Operación Bantotal");

        jLabel35.setText("Rubro");

        combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo1ActionPerformed(evt);
            }
        });

        jButton2.setText("Generar Rechazo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel36.setText("Motivo de rechazo del cheque: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tipInter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nroEnvio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nroCorrel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tipoItem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numBol, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numChe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(correCheque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bcoLib, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sucBcoLib, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(codPostal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(local, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ctaLibradora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(empCorresp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bancoCorres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sucBancoCorres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pzoEnHs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(codInter, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34)
                            .addComponent(jLabel35))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fecVencValor, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(trunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(impCheque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vencheque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(empBantotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sucBantotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(modBantotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ctaBantotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mdaBantotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(papBantotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sucDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mdaDeposito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fecDepo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(opBantotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(subOpBantotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tpoOpBantotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rubro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lincabt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lincabt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(sucDeposito, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(codInter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tipInter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mdaDeposito)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nroEnvio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nroCorrel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tipoItem))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(fecDepo)
                                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(fecVencValor)
                                            .addComponent(jLabel22))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(trunc)
                                            .addComponent(jLabel23))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(numBol)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(numChe)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(correCheque)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bcoLib)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sucBcoLib)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(codPostal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(local)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ctaLibradora)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(empCorresp)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bancoCorres)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sucBancoCorres)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pzoEnHs))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(impCheque)
                                            .addComponent(jLabel24))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(vencheque)
                                            .addComponent(jLabel25))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(empBantotal)
                                            .addComponent(jLabel26))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(sucBantotal)
                                            .addComponent(jLabel27))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(modBantotal)
                                            .addComponent(jLabel28))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(ctaBantotal)
                                            .addComponent(jLabel29))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(mdaBantotal)
                                            .addComponent(jLabel30))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(papBantotal)
                                            .addComponent(jLabel31))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(opBantotal)
                                            .addComponent(jLabel32))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(subOpBantotal)
                                            .addComponent(jLabel33))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(tpoOpBantotal)
                                            .addComponent(jLabel34))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(rubro)
                                            .addComponent(jLabel35))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(27, 27, 27))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        
        
        String lineacabt = lincabt.getText();
        System.out.println(lineacabt);
        
        String aCodInt = lineacabt.substring(0,3);
        codInter.setText(aCodInt);

        String aTipInt = lineacabt.substring(3,6);
        tipInter.setText(aTipInt);
        
        String nroEnvi = lineacabt.substring(6,15);
        nroEnvio.setText(nroEnvi);
        
        String nroCorre = lineacabt.substring(15,21);
        nroCorrel.setText(nroCorre);
        
        String tpoItem = lineacabt.substring(25,28);
        tipoItem.setText(tpoItem);
       
        String nroBoleta = lineacabt.substring(28, 37);
        numBol.setText(nroBoleta);
       
        String nroCheque = lineacabt.substring(37,52);
        numChe.setText(nroCheque);
       
        String corrCheque = lineacabt.substring(52, 67);
        correCheque.setText(corrCheque);
       
        String bcoLibr = lineacabt.substring(67, 70);
        bcoLib.setText(bcoLibr);
       
        String sucBco = lineacabt.substring(60, 73);
        sucBcoLib.setText(sucBco);
       
        String codPos = lineacabt.substring(73, 85);
        codPostal.setText(codPos);
       
        String localidad = lineacabt.substring(85, 88);
        local.setText(localidad);
       
        String ctaLibra = lineacabt.substring(88, 103);
        ctaLibradora.setText(ctaLibra);
       
        String empresaCorre = lineacabt.substring(103, 106);
        empCorresp.setText(empresaCorre);
        
        String bcoCorresp = lineacabt.substring(106, 109);
        bancoCorres.setText(bcoCorresp);
        
        String sucBcoCorresp = lineacabt.substring(109, 112);
        sucBancoCorres.setText(sucBcoCorresp);
        
        String pzoHs = lineacabt.substring(112, 115);
        pzoEnHs.setText(pzoHs);
        
        String sucDepo = lineacabt.substring(115, 118);
        sucDeposito.setText(sucDepo);  
        
        String mdaDepo = lineacabt.substring(118, 122);
        mdaDeposito.setText(mdaDepo); 
        
        String fechDepo = lineacabt.substring(122, 130);
        fecDepo.setText(fechDepo);
        
        String fechVencValor = lineacabt.substring(130, 138);
        fecVencValor.setText(fechVencValor);
        
        String truncado = lineacabt.substring(138, 139);
        trunc.setText(truncado);
        
        String importeCheque = lineacabt.substring(139, 157);
        impCheque.setText(importeCheque);
        
        String vencCheque = lineacabt.substring(157, 175);
        vencheque.setText(vencCheque);
        
        String empBt = lineacabt.substring(175, 178);
        empBantotal.setText(empBt);
        
        String sucBt = lineacabt.substring(178, 181);
        sucBantotal.setText(sucBt);
        
        String modBt = lineacabt.substring(181, 184);
        modBantotal.setText(modBt);
        
        String ctaBt = lineacabt.substring(184, 193);
        ctaBantotal.setText(ctaBt);
        
        String mdaBt = lineacabt.substring(193, 197);
        mdaBantotal.setText(mdaBt);
        
        String papBt = lineacabt.substring(197, 201);
        papBantotal.setText(papBt);
        
        String opBt = lineacabt.substring(201, 210);
        opBantotal.setText(opBt);
        
        String subOpBt = lineacabt.substring(210, 213);
        subOpBantotal.setText(subOpBt);
        
        String tpoOpBt = lineacabt.substring(213, 216);
        tpoOpBantotal.setText(tpoOpBt);
        
        String rbr = lineacabt.substring(216, 232);
        rubro.setText(rbr);
        
       


       jPanel1.setVisible(true);
         
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try
        {
            String texto = "CABTDREID.txt";
            File archivo=new File(texto);         //Le damos el nombre al archivo y la extension
            
            
            
            String categoria1 = (String) combo1.getSelectedItem();
            System.out.println(categoria1);
            String jcbom1 = categoria1;
            String motivorechazo = "";
            switch (jcbom1){
                case "CUENTA EMBARGADA":
                    motivorechazo = "01";
                    break;
                case "CTA.CERRADA P/ORDEN JUDIC.":
                    motivorechazo = "02";
                    break;
                case "CUENTA INEXISTENTE":
                    motivorechazo = "03";
                    break;
                case "NRO. DE CUENTA INVALIDO":
                    motivorechazo = "04";
                    break;
                case "ORDEN DE DIFERIMIENTO":
                    motivorechazo = "05";
                    break;
                case "DEFECTOS FORMALES":
                    motivorechazo = "06";
                    break;
                case "ORDEN DE NO PAGAR":
                    motivorechazo = "08";
                    break;
                case "SIN FDOS.SUFICIENTES EN CTA.":
                    motivorechazo = "10";
                    break;
                case "CHEQUE YA ENTREGADO ":
                    motivorechazo = "12";
                    break;
                case "SUC./ENTIDAD INEXISTENTE":
                    motivorechazo = "13";
                    break;
                case "ERROR DE FORMATO":
                    motivorechazo = "17";
                    break;
                case "FECHA DE COMPENS. ERRONEA":
                    motivorechazo = "18";
                    break;
                case "IMPORTE ERRONEO":
                    motivorechazo = "19";
                    break;
                case "CONCURSO PREVENTIVO":
                    motivorechazo = "21";
                    break;
                case "TRANSACCION DUPLICADA":
                    motivorechazo = "24";
                    break;
                case "ERROR EN REG. ADICIONAL":
                    motivorechazo = "25";
                    break;
                case "ERROR EN CAMPO MANDATORIO":
                    motivorechazo = "26";
                    break;
                case "ERROR EN CONTADOR REG.":
                    motivorechazo = "27";
                    break;
                case "VUELTA ATRAS DE CAMARA":
                    motivorechazo = "31";
                    break;
                case "SITUACION DE EMERGENCIA":
                    motivorechazo = "34";
                    break;
                case "FALTA CONFORMIDAD DE CHEQUERA":
                    motivorechazo = "35";
                    break;
                case "IMP. DISTINTO A TRANS ORIGINAL":
                    motivorechazo = "39";
                    break;
                case "CHEQ.EXTRAVIADO NO ENTREGADO":
                    motivorechazo = "44";
                    break;
                case "NO INDICO NRO. DE CHEQUE":
                    motivorechazo = "50";
                    break;
                case "FECHA INVALIDA":
                    motivorechazo = "75";
                    break;
                case "ERROR CAMPO 11 CAB. DE LOTE":
                    motivorechazo = "76";
                    break;
                case "ERROR CAMPO 4 REGISTRO INDIV.":
                    motivorechazo = "77";
                    break;
                case "ERROR CAMPO 5 REGISTRO INDIV.": 
                    motivorechazo = "78";
                    break;
                case "ERROR CAMPO 7 REGISTRO INDIV.":
                    motivorechazo = "79";
                    break;
                case "ERROR CAMPO 3 REG. ADICIONAL":
                    motivorechazo = "80";
                    break;
                case "FUERZA MAYOR":
                    motivorechazo = "81";
                    break;
                case "CHEQUE FALTANTE":
                    motivorechazo = "82";
                    break;
                case "MONEDA INVALIDA":
                    motivorechazo = "87";
                    break;
                case "ERROR CAMPO 2 REG. INDIVIDUAL":
                    motivorechazo = "88";
                    break;
                case "TRX. NO CORR. NO EX. ORIG.":
                    motivorechazo = "90";
                    break;
                case "COD. BCO. NO COMPAT. C/MONEDA":
                    motivorechazo = "91";
                    break;
                case "NRO. MAX. ORD. DIFER. EXCED.":
                    motivorechazo = "92";
                    break;
                case "DIA NO LABORABLE":
                    motivorechazo = "93";
                    break;
                case "CODIGO POSTAL ERRONEO":
                    motivorechazo = "94";
                    break;
                case "REVERSION YA EFECTUADA":
                    motivorechazo = "29";
                    break;
                case "FERIADO LOCAL":
                    motivorechazo = "09";
                    break;
                case "IMAGEN ILEGIBLE":
                    motivorechazo = "48";
                    break;
            }  
            
            
            
            
            
            
            
            if (archivo.exists()) {
                   archivo.delete();
               }
            
                        try (FileWriter escribir = new FileWriter(archivo,true)) {
                //Escribimos en el archivo con el metodo write
                        String lineacabt = lincabt.getText();
                        String graba = lineacabt.substring(0, 3);
                             
                        String grabado = lineacabt.substring(6, 233);
                        String codigo = "003";
                        String motiRech = motivorechazo;
                        String relleno = "00";
                        String relleno2 = "                                                  ";
                        String relleno3 = "                                                  ";
                        String relleno4 = "                                                  ";
                        String relleno5 = "00000000";
                        
                escribir.write(graba+codigo+grabado+motiRech+relleno+relleno2+relleno3+relleno4+relleno5+"\r\n");
            }
                        //Lo utilizamos para limpiar los textFields

            this.dispose();
            new agregarendolares(this, true).setVisible(true);
        }


        //En caso de error.
        catch(Exception e)
        {
            System.out.println("Error al escribir");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cabtdreid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cabtdreid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cabtdreid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cabtdreid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new cabtdreid();
                frame.setVisible(true);
                frame.setLocationRelativeTo(null);
                
                
            }
            
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bancoCorres;
    private javax.swing.JLabel bcoLib;
    private javax.swing.JLabel codInter;
    private javax.swing.JLabel codPostal;
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JLabel correCheque;
    private javax.swing.JLabel ctaBantotal;
    private javax.swing.JLabel ctaLibradora;
    private javax.swing.JLabel empBantotal;
    private javax.swing.JLabel empCorresp;
    private javax.swing.JLabel fecDepo;
    private javax.swing.JLabel fecVencValor;
    private javax.swing.JLabel impCheque;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lincabt;
    private javax.swing.JLabel local;
    private javax.swing.JLabel mdaBantotal;
    private javax.swing.JLabel mdaDeposito;
    private javax.swing.JLabel modBantotal;
    private javax.swing.JLabel nroCorrel;
    private javax.swing.JLabel nroEnvio;
    private javax.swing.JLabel numBol;
    private javax.swing.JLabel numChe;
    private javax.swing.JLabel opBantotal;
    private javax.swing.JLabel papBantotal;
    private javax.swing.JLabel pzoEnHs;
    private javax.swing.JLabel rubro;
    private javax.swing.JLabel subOpBantotal;
    private javax.swing.JLabel sucBancoCorres;
    private javax.swing.JLabel sucBantotal;
    private javax.swing.JLabel sucBcoLib;
    private javax.swing.JLabel sucDeposito;
    private javax.swing.JLabel tipInter;
    private javax.swing.JLabel tipoItem;
    private javax.swing.JLabel tpoOpBantotal;
    private javax.swing.JLabel trunc;
    private javax.swing.JLabel vencheque;
    // End of variables declaration//GEN-END:variables
}
