/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package genar;

import java.io.File;
import java.io.FileWriter;

/**
 *
 * @author pzanelli
 */
public class CABTDCEIP extends javax.swing.JFrame {

        public static class Variable {
        public static String fecha = "";
        public static String nroEnvio1 = "";
        public static String nroBoleta = "";
    }
    
    
    /**
     * Creates new form camararecibida
     */
    public CABTDCEIP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nroEnvio = new javax.swing.JTextField();
        cantDeChq = new javax.swing.JTextField();
        ctaBantotal = new javax.swing.JTextField();
        sucBantotal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        subCtaBantotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tpoPer = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        nroBoleta = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fechaDeposito = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        importeBoleta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Canje Interno CABTDCEIP");
        setAlwaysOnTop(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Generación archivo para generar archivo CABTDCEIP");

        jLabel2.setText("Número de Envio");

        jLabel3.setText("Cantidad de Cheques");

        jLabel5.setText("Cuenta Bantotal");

        jLabel6.setText("Sucursal Bantotal");

        jButton1.setText("Generar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Sub-Cuenta Bantotal");

        jLabel8.setText("Tipo de operacion");

        jLabel9.setText("Número de Boleta");

        jLabel10.setText("Fecha del Depósito");

        jLabel11.setText("Importe de la Boleta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(subCtaBantotal)
                            .addComponent(cantDeChq)
                            .addComponent(ctaBantotal, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sucBantotal, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nroEnvio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tpoPer)
                            .addComponent(nroBoleta, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechaDeposito)
                            .addComponent(importeBoleta)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nroEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nroBoleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantDeChq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(importeBoleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sucBantotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ctaBantotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subCtaBantotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tpoPer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String codInt = "003"; //
        String tipInt = "002"; //
        String numEnv = nroEnvio.getText(); //
        String corre = "0000000001"; //
        String tipItem = "001"; //
        String numBole = nroBoleta.getText(); //
        String numCheque = "000000000000000";  // 
        String cantCheq = cantDeChq.getText(); //
        String sucDeposito = "100"; // 
        String mndaDeposito = "0080"; //
        String fechaDeposit = fechaDeposito.getText();//
        String fechVencValor = "00000000"; //
        String importeBole = importeBoleta.getText(); //
        String empresa = "001";
        String sucBcoCorresp = sucBantotal.getText();
        String modBt = "0200";
        String ctaBt = ctaBantotal.getText();
        String mdaDepo = "0080";    
        String papelBt = "0000"; //Completar con 8 digitos
        String operBantotal = "000000000";
        String subOper = subCtaBantotal.getText();
        String tpoOper = tpoPer.getText();  //Completar con 18 digitos
        String rubro = "0000000311724001";
        
        
      
        

        try
        {
            String texto = "CABTDCEIP.txt";
            File archivo=new File(texto);         //Le damos el nombre al archivo y la extension
            
            String numEnv2 = String.format("%09d", Integer.parseInt(numEnv));
            String numBole2 = String.format("%09d", Integer.parseInt(numBole));
            String cantChq2 = String.format("%015d", Integer.parseInt(cantCheq));
            String importeBole2 = String.format("%018d", Integer.parseInt(importeBole));
            String sucBcoCorresp2 = String.format("%03d", Integer.parseInt(sucBcoCorresp));
            String ctaBt2 = String.format("%08d", Integer.parseInt(ctaBt));
            String subOper2 = String.format("%03d", Integer.parseInt(subOper));
            String tpoOper2 = String.format("%03d", Integer.parseInt(tpoOper));
            Variable.fecha = fechaDeposit;
            Variable.nroEnvio1 = numEnv2;
            Variable.nroBoleta = numBole2;
            //Importe proveedor igual al importe de boleta
            
            
            
            //Comprobamos que si el archivo exista, lo borre. 
            if (archivo.exists()) {
                   archivo.delete();
               }
                        try (FileWriter escribir = new FileWriter(archivo,true)) {
                //Escribimos en el archivo con el metodo write                          
                escribir.write(codInt+tipInt+numEnv2+corre+tipItem+numBole2+numCheque+cantChq2+sucDeposito+mndaDeposito+fechaDeposit+
                        fechVencValor+importeBole2+importeBole2+empresa+sucBcoCorresp2+modBt+ctaBt2+mdaDepo+papelBt+operBantotal+
                        subOper2+tpoOper2+rubro+"\r\n");
            }
                        //Lo utilizamos para limpiar los textFields

            this.dispose();
            new agregarchqcanje(this, true).setVisible(true);
        }
        //En caso de error.
        catch(Exception e)
        {
            System.out.println("Error al escribir");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CABTDCEIP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CABTDCEIP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CABTDCEIP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CABTDCEIP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CABTDCEIP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cantDeChq;
    private javax.swing.JTextField ctaBantotal;
    private javax.swing.JTextField fechaDeposito;
    private javax.swing.JTextField importeBoleta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nroBoleta;
    private javax.swing.JTextField nroEnvio;
    private javax.swing.JTextField subCtaBantotal;
    private javax.swing.JTextField sucBantotal;
    private javax.swing.JTextField tpoPer;
    // End of variables declaration//GEN-END:variables
}
